Manage Data Model In Blog App
Atril33/blog_app pull request #1
Opened 2023-06-28 17:46 UTC by Atril33

2023-06-28 20:10 UTC, DuaneDave requested changes
Hi @Atril33 👋 , 

Good job so far on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Rails has been correctly used
✔️ Correct use of gitflow

## Required Changes ♻️
- Since you are using the wrong db set-up, the syntax you are using in your migration files is not in accordance with the expected syntax for Postgres. Consider addressing that in order to stay within the scope of the project

_Check the comments under the review._

## Optional suggestions
N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-29 10:28 UTC, Gambit142 requested changes
Hi @Atril33 👋, 

Great work on making the changes requested by a previous reviewer 👏 

## Highlights
- All linters checks passed ✔️ 
- Created Migration files for the `User`, `Comment`, `Post` and `Like` models ✔️ 
- Used _**PostgreSQL**_ as database for the application ✔️ 

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions

- Kindly consider the comments tagged [OPTIONAL] under this review summary 👍 💻 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer and addressing them will improve your application._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-29 10:28 UTC, Gambit142 commented on README.md
- [OPTIONAL] The link to your LICENSE is broken and displays a 404 error page. Kindly input the correct link. 👍

2023-06-29 10:28 UTC, Gambit142 commented on db/migrate/20230628162412_create_user.rb
> +      t.datetime :updatedAt
- [ ] Kindly add the `posts_counter` column to this table in this migration file. Based on this [schema](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png), there is a `posts_counter` column in the `Users` table and it should have the type integer. Kindly implement this change. 👍 😎

2023-06-29 10:28 UTC, Gambit142 commented on db/migrate/20230628162603_create_post.rb
> +      t.timestamps
- [ ] Great work creating this migration file. As mentioned by the previous reviewer, you created an `author_id` column. The way you created this column, it is not linked to the `User` table. Rails will assume that it is meant to be a normal column and not a foreign key. I would advise you to remove the `author_id` column and create this migration the way the previous reviewer asked you to. 💻 🖱️ 

```ruby
create_table :posts do |t|
    t.string :title
    t.text :text
    t.integer :comments_counter
    t.integer :likes_counter
    t.timestamps # this will crate updated_at and created_at columns
    t.references :author, foreign_key: { to_table: 'users' } # this will create author_id and a corresponding index 
  end
```

2023-06-29 10:28 UTC, Gambit142 commented on db/migrate/20230629091742_create_like.rb
> +end
- [ ] Great work implementing this change suggested by the previous reviewer. However, you didn't remove these lines of codes:

```ruby
t.integer :author_id
t.integer :post_idt
```
The other lines of code will create the foreign key needed. 👍 😎

2023-06-29 10:28 UTC, Gambit142 commented on db/migrate/20230629092125_create_comment.rb
> +end
- [ ] Great work implementing this change suggested by the previous reviewer. However, you didn't remove these lines of codes:

```ruby
t.integer :author_id
t.integer :post_id
```
The other lines of code will create the foreign key needed. Kindly remove the first two columns 💻 🖱️

2023-06-29 11:19 UTC, FrederickMih requested changes
## Hi :raising_hand: :raising_hand: @Atril33 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

- Great job removing the unnecessary columns in some tables :+1: 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-29 11:19 UTC, FrederickMih commented on db/migrate/20230629092125_create_comment.rb
> +      t.integer :post_id
- [ ] Hi @Atril33, you fixed the other issues mentioned by the previous reviewer and forgot this one. Rails do this automatically for you. Let's kindly get rid of these columns. Lines 7 and 8 are going to create these two lines in the comments table for free to you :smile:  when you run rails db:migrate

2023-06-29 11:34 UTC, uwadonat approved these changes
## Hi @Atril33,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉
### Highlights
- Good commit messages ✔️
- Well organized and clean project ✔
![appr](https://github.com/Atril33/blog_app/assets/65860678/dfc55ddb-7007-4a24-bbdd-a9df711c03b3)

# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-06-29 11:48 UTC, merged