Processing Data In Blog App
Atril33/blog_app pull request #2
Opened 2023-06-30 16:26 UTC by Atril33

2023-06-30 16:49 UTC, peterrobert requested changes
Hi @Atril33 , 

Very nice project. Great work with your associations. 👏🏿 . However, there are a few changes to be made kindly check below ⬇️

### Highlights!

[ ] Good feature branch name ✔️
[ ] Descriptive pull request ✔️


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or tag me @peterrobert if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-30 16:49 UTC, peterrobert commented on db/migrate/20230630125815_add_comments_counter_to_posts.rb
> +end
- [ ] It will be great to ensure that the migrations run successfully. When I try running your migrations, the following error pops up ⬇️ 
<img width="1220" alt="Screenshot 2023-06-30 at 19 42 30" src="https://github.com/Atril33/blog_app/assets/32361963/1b4b7cd1-e573-400c-9fe4-465eedf9004b">

After trying to track the problem, I noticed you have created a migration for adding the comments_counter and it is already there in your posts migration. Kindly fix this issue

2023-06-30 16:49 UTC, peterrobert commented on db/migrate/20230630153724_add_posts_counter_to_users.rb
> +  end
- [ ] It will be great to ensure that the migrations run successfully. When I try running your migrations, the following error pops up ⬇️ 
<img width="1220" alt="Screenshot 2023-06-30 at 19 42 30" src="https://github.com/Atril33/blog_app/assets/32361963/1b4b7cd1-e573-400c-9fe4-465eedf9004b">

After trying to track the problem, I noticed you have created a migration for adding the posts_counter and it is already there in your user's migration. Kindly fix this issue. Ensure that there is no duplication in your migrations in order for it to run successfully

2023-06-30 17:16 UTC, Atril33 commented on db/migrate/20230630153724_add_posts_counter_to_users.rb
> +  end
Hello @peterrobert, thank you for your golden time and your informative feedback. But I am worried that everything thing is working fine from my end so how should I make changes in my code? Would you like to let me know which command did you use for running migrations?

2023-07-01 03:41 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi Syed,  

Your project is complete! 🏁 There is nothing else to say other than... it's time to merge it 🍾 Congratulations!  🎉💯🌟 

## Highlights 🎯 
🎲 Good job on implementing recommended changes!

## Optional suggestions 🧰 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

_Kindly consider my inline comments marked **[OPTIONAL]** under this review_


Cheers..Happy coding!💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-01 03:41 UTC, rloterh commented on app/models/post.rb
> +    belongs_to :author, class_name: 'User', foreign_key: 'author_id'
- [ ] [OPTIONAL]
The `id` of _Post_ is supposed to reference the foreign key `author_id` of the _User_ model (and also declared in the _User_ model), and hence it's redundant to declare `author_id` as a foreign key in _Post_ model. Let's simply do something like this:
```ruby
# app/models/post.rb
belongs_to :author, class_name: 'User'

2023-07-01 03:41 UTC, rloterh commented on app/models/comment.rb
> +    belongs_to :author, class_name: 'User', foreign_key: 'author_id'
- [ ] [OPTIONAL]
Again, the `id` of _Comment_ is supposed to reference the foreign key `author_id` of the _User_ model (and also declared in the _User_ model), and hence it's redundant to declare `author_id` as a foreign key in _Comment_ model. Let's simply do something like this:
```ruby
# app/models/;comment.rb
belongs_to :author, class_name: 'User'

2023-07-01 03:41 UTC, rloterh commented on app/models/like.rb
> +    belongs_to :author, class_name: 'User', foreign_key: 'author_id'
- [ ] [OPTIONAL]
Again, the `id` of _Like_ is supposed to reference the foreign key `author_id` of the _User_ model (and also declared in the _User_ model), and hence it's redundant to declare `author_id` as a foreign key in _Like_ model. Let's simply do something like this:
```ruby
# app/models/;like.rb
belongs_to :author, class_name: 'User'

2023-07-01 03:41 UTC, rloterh commented on app/models/post.rb
> +    end
- [ ] [OPTIONAL]
it's a good practice to use one of the Rails Active Callbacks `after_save` to call the `update_post_counter` method every time a new post has been saved to the database, and when `after_save` is called mark the `update_post_counter` method as _private_ accordingly, which should be similar to:

```ruby
 # app/models/post.rb
  after_save :update_post_counter

  private

  def update_post_counter
    author.increment!(:posts_counter)
  end
```

2023-07-01 03:41 UTC, rloterh commented on app/models/comment.rb
> +      post.update(comments_counter: post.comments.count)
- [ ] [OPTIONAL]
Following best practices `update_comments_counter` should be marked as _private_ after implementing the `after_create` method.

2023-07-01 03:41 UTC, rloterh commented on app/models/like.rb
> +    end
- [ ] [OPTIONAL]
Following best practices `update_likes_counter` should be marked as _private_ after implementing the `after_save` method.

2023-07-01 04:16 UTC, merged