Setup Controllers, Views & Actions
Atril33/blog_app pull request #4
Opened 2023-07-04 16:36 UTC by Atril33

2023-07-04 17:25 UTC, Gambit142 requested changes
Hi @Atril33 👋, 

Good job so far!

## Highlights
- All linters checks passed ✔️ 
- Created `Users` controller with `index` and `show` actions ✔️ 
- Created `Posts` controller with `index` and `show` actions ✔️
- Created routes to map the controllers. ✔️  

You still need to work on some issues to go to the next project, but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

You can also consider the following:

N/A

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-07-04 17:25 UTC, Gambit142 commented on config/routes.rb
>  end
- [ ] Great work creating this URL. However, I noticed that you have two `:id` parameters in this URL. What this means is that you will most likely query the database wrongly if you want to get the User of the posts through Rails `params` hash because the `params` hash will supply the `:id` of the post always as it is the last expression. 💻 For example, if we have a URL in the browser that is like this `http://localhost:3000/users/2/posts/1`. The `:id` in the params hash will always return the value `'1'`. Meanwhile, the user's `ID` in the database is`2` but you might end up searching for the wrong user with ID `1` because you have params `:id` as `1` 😄. This log explains better:

![image](https://github.com/Atril33/blog_app/assets/77106962/eca6690c-fe34-4790-b757-276f040082dc)

#### Hint: Use `:user_id` instead of `:id` to get the ID of the user. SO your route should look like this:

```ruby
get '/users/:user_id/posts/:id', to: 'posts#show'
```

#### This will return params `:user_id` for the user's `ID` and params `:id` for the post's `ID` 👍 😎 . If done this way, and you put this URL in the browser `http://localhost:3000/users/2/posts/1`, you will have the log output this:

![image](https://github.com/Atril33/blog_app/assets/77106962/7ad06b1e-c358-47bb-8310-46a5ec0b3b4f)

2023-07-05 04:43 UTC, BenMukebo commented on config/routes.rb
>  end
- Well said @Gambit142 💯 👏🏻 :
- You may also consider doing the same or the post, since later on you will have the `Comment` and `Like` tables so that your code may look like this: 

```ruby
  get '/users/:user_id/posts/:post_id/comments', to: 'posts#show'
  get '/users/:user_id/posts/:post_id/likes', to: 'posts#show'
```

2023-07-05 04:45 UTC, BenMukebo approved these changes
### Hi @Atril33, 👋 

# STATUS: Approved  🎉 

Great work on making the changes requested by a previous reviewer :1st_place_medal:  
 Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)

### To Highlight :1st_place_medal: 
- Your Pull Request has a proper title and description. ✔️  
- No Linter errors :heavy_check_mark: 
- Professional README file. 👍🏻 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-05 05:32 UTC, merged